"""Seed script to register 17 top global tech companies and generate 74 realistic jobs across all 20 standard roles."""
import os
import sys
from datetime import datetime, timezone
import bcrypt
from bson import ObjectId
from pymongo import MongoClient

MONGODB_URI = os.getenv("MONGODB_URI")
if not MONGODB_URI:
    print("FATAL: MONGODB_URI not set. Copy .env.example to .env and fill credentials.", file=sys.stderr)
    sys.exit(1)
DB_NAME = os.getenv("DB_NAME", "HR")

client = MongoClient(MONGODB_URI)
db = client[DB_NAME]

def hash_pw(pw: str) -> str:
    return bcrypt.hashpw(pw.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")

COMPANIES_70 = [
    {
        "company_name": "Netflix",
        "email": "careers@netflix.com",
        "password": "Password123!",
        "industry": "Entertainment & Streaming Media",
        "website": "https://jobs.netflix.com",
        "jobs": [
            {
                "title": "Backend Developer",
                "department": "Content Delivery & Playback Core",
                "employment_type": "Full-time",
                "location": "Los Gatos, CA (Hybrid)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Node.js", "Python", "REST APIs", "PostgreSQL", "Redis", "Docker", "Java"],
                "preferred_skills": ["gRPC", "Kafka", "High Throughput Caching", "Microservices"],
                "description": "Architect edge services and video distribution microservices handling over 250 million concurrent video streams globally with ultra-low latency.",
                "responsibilities": "Design distributed microservices in Java/Python, optimize Redis caching clusters, and build adaptive bitrate delivery APIs.",
                "salary_range": "$170,000 - $240,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Data Scientist",
                "department": "Personalization & Recommendation Algorithms",
                "employment_type": "Full-time",
                "location": "Los Gatos, CA (Remote)",
                "experience_required": 4,
                "education_required": "Master's or Ph.D. in Statistics, Machine Learning, or CS",
                "required_skills": ["Python", "R", "Machine Learning", "SQL", "Statistics", "Pandas"],
                "preferred_skills": ["Collaborative Filtering", "Reinforcement Learning", "A/B Testing"],
                "description": "Develop state-of-the-art recommendation systems and ranking algorithms that personalize the Netflix home screen for members worldwide.",
                "responsibilities": "Formulate multi-armed bandit models, design global offline/online evaluation experiments, and optimize personalized content artwork.",
                "salary_range": "$180,000 - $260,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Site Reliability Engineer",
                "department": "Cloud Telemetry & Chaos Engineering",
                "employment_type": "Full-time",
                "location": "Los Gatos, CA (Hybrid)",
                "experience_required": 5,
                "education_required": "Bachelor's in Computer Science or Systems Engineering",
                "required_skills": ["Kubernetes", "Prometheus", "Linux", "Incident Management", "Python", "Go", "CI/CD"],
                "preferred_skills": ["Chaos Monkey", "Spinnaker", "Distributed Tracing", "AWS Multi-Region"],
                "description": "Build automated resilience platforms and chaos testing frameworks ensuring Netflix streaming operates uninterrupted during AWS regional outages.",
                "responsibilities": "Execute chaos injection drills, manage real-time observability pipelines, and automate self-healing infrastructure.",
                "salary_range": "$175,000 - $245,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Frontend Developer",
                "department": "TV & Living Room Web UI",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Web Development",
                "required_skills": ["React", "JavaScript", "TypeScript", "HTML/CSS", "Redux", "Tailwind"],
                "preferred_skills": ["React Native for TV", "WebGL", "Memory Optimization for Low-End Devices"],
                "description": "Engineer high-performance client applications rendered across hundreds of smart TVs, gaming consoles, and streaming set-top devices.",
                "responsibilities": "Optimize animation frame rates, implement focus management for remote controllers, and maintain lightweight bundle sizes.",
                "salary_range": "$155,000 - $210,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "UI/UX Designer",
                "department": "Global Product Design",
                "employment_type": "Full-time",
                "location": "Los Gatos, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in HCI, Visual Design, or Product Design",
                "required_skills": ["Figma", "Adobe XD", "Wireframing", "User Research", "Prototyping"],
                "preferred_skills": ["Living Room UX", "Design Systems (Hawkins)", "Motion Graphics"],
                "description": "Design cinematic, intuitive UI experiences that seamlessly guide users from browsing to watching their favorite movies and TV shows.",
                "responsibilities": "Create wireframes, high-fidelity prototypes, and motion specs for mobile, tablet, desktop, and 10-foot television interfaces.",
                "salary_range": "$145,000 - $195,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Spotify",
        "email": "careers@spotify.com",
        "password": "Password123!",
        "industry": "Audio Streaming & Music Technology",
        "website": "https://www.lifeatspotify.com",
        "jobs": [
            {
                "title": "Machine Learning Engineer",
                "department": "Audio Intelligence & Discover Weekly",
                "employment_type": "Full-time",
                "location": "New York, NY (Hybrid)",
                "experience_required": 4,
                "education_required": "Master's in Machine Learning, DSP, or Computer Science",
                "required_skills": ["Python", "PyTorch", "TensorFlow", "MLOps", "Docker", "NLP"],
                "preferred_skills": ["Audio Signal Processing", "Vector Search", "GCP Vertex AI", "Transformers"],
                "description": "Train deep learning models that analyze raw audio waveform acoustic features, genre classification, and listener intent for personalized playlist curation.",
                "responsibilities": "Develop audio embedding models, build real-time vector search indexers, and productionize low-latency recommendation inference pipelines.",
                "salary_range": "$160,000 - $220,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Mobile App Developer",
                "department": "Spotify iOS & Android Core",
                "employment_type": "Full-time",
                "location": "Boston, MA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Flutter", "React Native", "iOS", "Android", "Swift", "Kotlin"],
                "preferred_skills": ["CoreAudio", "ExoPlayer", "Offline Storage Synchronization", "C++ NDK"],
                "description": "Build smooth, high-fidelity audio playback and playlist synchronization features used daily by over 500 million active listeners.",
                "responsibilities": "Develop native Swift and Kotlin audio buffer rendering modules, reduce background battery drain, and build interactive Canvas video playback.",
                "salary_range": "$145,000 - $195,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Data Engineer",
                "department": "Global Royalty & Listener Data Platform",
                "employment_type": "Full-time",
                "location": "New York, NY (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Data Engineering, CS, or Applied Mathematics",
                "required_skills": ["SQL", "Apache Spark", "Python", "ETL Pipelines", "Kafka", "BigQuery"],
                "preferred_skills": ["GCP Dataflow", "Scio / Scala", "dbt", "Airflow"],
                "description": "Scale petabyte-scale data pipelines processing tens of billions of daily stream events for royalty payouts and artist analytics.",
                "responsibilities": "Build exactly-once event streaming pipelines, design BigQuery analytical schemas, and optimize large-scale Spark transformations.",
                "salary_range": "$140,000 - $190,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "QA/Test Automation Engineer",
                "department": "Multi-Platform Quality & Device Ecosystem",
                "employment_type": "Full-time",
                "location": "New York, NY (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Selenium", "Cypress", "TestNG", "Python", "JIRA", "CI/CD"],
                "preferred_skills": ["Appium", "Hardware Device Farms", "Audio Playback Test Automation"],
                "description": "Develop multi-device automated testing harnesses ensuring audio sync, Bluetooth streaming, and UI fluidity across hundreds of mobile and car platforms.",
                "responsibilities": "Create automated end-to-end regression tests, implement continuous performance benchmarking in CI/CD, and validate car audio integrations.",
                "salary_range": "$125,000 - $165,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Business/Systems Analyst",
                "department": "Artist & Label Monetization Strategy",
                "employment_type": "Full-time",
                "location": "Los Angeles, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Business Analytics, Finance, or Information Systems",
                "required_skills": ["Requirements Gathering", "SQL", "Agile", "UML", "JIRA", "Business Process"],
                "preferred_skills": ["Music Licensing Regulations", "Financial Modeling", "Looker"],
                "description": "Collaborate with record labels, publishers, and product teams to translate complex global music royalty structures into engineering requirements.",
                "responsibilities": "Analyze streaming payout calculations, author detailed technical user stories, and track feature delivery across monetization squads.",
                "salary_range": "$120,000 - $165,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Stripe",
        "email": "careers@stripe.com",
        "password": "Password123!",
        "industry": "Financial Infrastructure & Online Payments",
        "website": "https://stripe.com/jobs",
        "jobs": [
            {
                "title": "Software Engineer",
                "department": "Payments Core & Ledger Engine",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Python", "Java", "Git", "REST APIs", "SQL", "Data Structures"],
                "preferred_skills": ["Ruby / Sorbet", "Distributed Transactions", "Idempotency Architectures"],
                "description": "Build mission-critical payment infrastructure that processes hundreds of billions of dollars annually for millions of internet businesses.",
                "responsibilities": "Implement fault-tolerant payment APIs, guarantee double-entry accounting ledger consistency, and maintain five-nines uptime.",
                "salary_range": "$165,000 - $230,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Cybersecurity Analyst",
                "department": "Fraud Prevention & Financial Threat Defense",
                "employment_type": "Full-time",
                "location": "Seattle, WA (Remote)",
                "experience_required": 4,
                "education_required": "Bachelor's in Cybersecurity, CS, or Information Assurance",
                "required_skills": ["Network Security", "SIEM", "Firewalls", "Threat Analysis", "Linux", "Python"],
                "preferred_skills": ["Radar ML integration", "PCI-DSS Level 1 Compliance", "Carding Attack Defense"],
                "description": "Protect internet merchants from sophisticated financial fraud rings, credential stuffing, and card-testing cyber attacks.",
                "responsibilities": "Analyze fraudulent transaction patterns, build automated IP/fingerprint mitigation rules, and coordinate incident response.",
                "salary_range": "$150,000 - $205,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Database Administrator",
                "department": "Global Financial Database Infrastructure",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 5,
                "education_required": "Bachelor's in Computer Science or Database Systems",
                "required_skills": ["PostgreSQL", "MySQL", "Database Tuning", "SQL", "Backup & Recovery"],
                "preferred_skills": ["Database Sharding", "Distributed SQL", "Point-in-Time Recovery", "Zero-Loss Replication"],
                "description": "Scale and safeguard the global relational database infrastructure powering Stripe's primary transactions, ledger balances, and payouts.",
                "responsibilities": "Optimize heavy OLTP queries, orchestrate live shard splits without downtime, and validate immutable transactional backup systems.",
                "salary_range": "$160,000 - $220,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "DevOps Engineer",
                "department": "Developer Infrastructure & Continuous Delivery",
                "employment_type": "Full-time",
                "location": "New York, NY (Hybrid)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science or Systems Engineering",
                "required_skills": ["Docker", "Kubernetes", "CI/CD", "AWS", "Terraform", "Linux"],
                "preferred_skills": ["Bazel", "Canary Deployments", "Policy-as-Code (OPA)", "Zero-Trust Mesh"],
                "description": "Design secure deployment pipelines and automated cloud testing infrastructure that allows hundreds of engineers to safely deploy code dozens of times a day.",
                "responsibilities": "Manage Kubernetes fleets across multiple cloud regions, enforce strict security compliance in CI/CD, and accelerate build execution times.",
                "salary_range": "$155,000 - $215,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Full Stack Developer",
                "department": "Stripe Dashboard & Billing UI",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Web Engineering",
                "required_skills": ["React", "Node.js", "TypeScript", "PostgreSQL", "Docker", "Git"],
                "preferred_skills": ["GraphQL", "Micro-frontend Architecture", "Data Visualization (D3)"],
                "description": "Craft responsive web dashboards that give founders and finance executives instant visibility into subscription revenues, dispute resolutions, and invoices.",
                "responsibilities": "Develop interactive financial charts and report generation tools in React/TypeScript and write robust GraphQL/REST backend resolvers.",
                "salary_range": "$150,000 - $205,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Uber",
        "email": "careers@uber.com",
        "password": "Password123!",
        "industry": "Ridesharing, Logistics & Autonomous Mobility",
        "website": "https://www.uber.com/careers",
        "jobs": [
            {
                "title": "Software Engineer",
                "department": "Marketplace Dynamic Pricing & Dispatch",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Python", "Java", "Git", "REST APIs", "SQL", "Data Structures", "Go"],
                "preferred_skills": ["H3 Spatial Indexing", "Real-Time Matching", "High Concurrency"],
                "description": "Build high-speed real-time dispatch algorithms matching millions of riders with nearby drivers in sub-second latency.",
                "responsibilities": "Develop distributed matching microservices in Go and Java, optimize geospatial queries, and maintain real-time supply/demand heatmaps.",
                "salary_range": "$155,000 - $215,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Mobile App Developer",
                "department": "Rider & Driver Core Applications",
                "employment_type": "Full-time",
                "location": "Seattle, WA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Mobile Engineering",
                "required_skills": ["Flutter", "React Native", "iOS", "Android", "Swift", "Kotlin"],
                "preferred_skills": ["RIBs Architecture", "Mapbox SDK", "Location Tracking Battery Optimization"],
                "description": "Develop mission-critical native mobile apps for millions of riders and drivers operating on roads across 70+ countries.",
                "responsibilities": "Engineer turn-by-turn navigation interfaces, reduce GPS location battery consumption, and implement real-time safety telemetry.",
                "salary_range": "$150,000 - $200,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Data Scientist",
                "department": "Supply/Demand Forecasting & Marketplace Insights",
                "employment_type": "Full-time",
                "location": "Sunnyvale, CA (Hybrid)",
                "experience_required": 4,
                "education_required": "Master's or Ph.D. in Operations Research, Statistics, or CS",
                "required_skills": ["Python", "R", "Machine Learning", "SQL", "Statistics", "Pandas"],
                "preferred_skills": ["Time-Series Forecasting", "Spatial Econometrics", "Deep Q-Learning"],
                "description": "Formulate predictive models that forecast localized ride demand, optimal surge pricing curves, and driver positioning strategies.",
                "responsibilities": "Build time-series forecasting models, analyze market elasticity, and design large-scale randomized geographic switchback experiments.",
                "salary_range": "$160,000 - $225,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_count": 10,
            },
            {
                "title": "Cloud Solutions Architect",
                "department": "Multi-Cloud Infrastructure & Edge Ingestion",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 5,
                "education_required": "Bachelor's in Computer Science or Systems Engineering",
                "required_skills": ["AWS", "Azure", "Cloud Architecture", "Terraform", "Docker", "Microservices"],
                "preferred_skills": ["Hybrid Cloud Networking", "GCP Interconnect", "Cost Optimization"],
                "description": "Architect high-availability cloud foundations bridging on-premise compute centers with AWS and GCP multi-cloud regions.",
                "responsibilities": "Formulate hybrid-cloud infrastructure architectures, optimize multi-million dollar cloud compute spend, and guarantee disaster failover.",
                "salary_range": "$165,000 - $230,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Embedded Systems Engineer",
                "department": "Autonomous Vehicle Hardware Telemetry",
                "employment_type": "Full-time",
                "location": "Pittsburgh, PA (On-site)",
                "experience_required": 4,
                "education_required": "Bachelor's or Master's in Electrical/Embedded Systems Engineering",
                "required_skills": ["C", "C++", "RTOS", "Microcontrollers", "Embedded Linux", "I2C/SPI"],
                "preferred_skills": ["CAN Bus", "LiDAR/Camera Sensor Fusion", "AUTOSAR", "Safety-Critical Systems"],
                "description": "Design firmware for custom IoT telemetry beacons and sensor gateways deployed on commercial vehicle fleets and delivery robotics.",
                "responsibilities": "Write real-time CAN bus telemetry parsers, develop firmware OTA update protocols, and interface microcontrollers with inertial sensors.",
                "salary_range": "$150,000 - $210,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Airbnb",
        "email": "careers@airbnb.com",
        "password": "Password123!",
        "industry": "Travel, Hospitality & Marketplace Technology",
        "website": "https://careers.airbnb.com",
        "jobs": [
            {
                "title": "Frontend Developer",
                "department": "Guest Booking & Search Experience",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Web Engineering",
                "required_skills": ["React", "JavaScript", "TypeScript", "HTML/CSS", "Redux", "Tailwind"],
                "preferred_skills": ["Server-Side Rendering", "Accessible Design (WCAG)", "Performance Profiling"],
                "description": "Build immersive, fluid search and interactive map booking flows helping travelers discover unique homes across 100,000+ cities worldwide.",
                "responsibilities": "Develop modular UI components, optimize image rendering and map search performance, and implement seamless internationalization.",
                "salary_range": "$145,000 - $195,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "UI/UX Designer",
                "department": "Host Tools & Pricing Experience",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Interaction Design, HCI, or Design",
                "required_skills": ["Figma", "Adobe XD", "Wireframing", "User Research", "Prototyping"],
                "preferred_skills": ["Design Systems", "Marketplace Host UX", "Qualitative User Testing"],
                "description": "Empower millions of Airbnb hosts by designing intuitive calendar management, smart pricing controls, and reservation messaging tools.",
                "responsibilities": "Lead user research interviews with hosts globally, prototype responsive desktop/mobile layouts in Figma, and build cohesive design system guidelines.",
                "salary_range": "$140,000 - $190,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Full Stack Developer",
                "department": "Host Onboarding & Identity Verification",
                "employment_type": "Full-time",
                "location": "Seattle, WA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["React", "Node.js", "TypeScript", "PostgreSQL", "Docker", "Git"],
                "preferred_skills": ["Java / Kotlin Services", "GraphQL", "DocuSign / ID Integration"],
                "description": "Engineer end-to-end listing creation and biometric host identity verification pipelines ensuring trust and safety across the platform.",
                "responsibilities": "Build step-by-step listing wizard flows in React, author robust Kotlin/Java microservices, and integrate automated ID verification workflows.",
                "salary_range": "$150,000 - $205,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Data Engineer",
                "department": "Search Ranking & Analytics Pipeline",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science, Data Engineering, or Math",
                "required_skills": ["SQL", "Apache Spark", "Python", "ETL Pipelines", "Kafka", "BigQuery"],
                "preferred_skills": ["Apache Airflow", "Apache Iceberg", "Presto / Trino", "Feature Stores"],
                "description": "Design high-throughput data pipelines that feed offline training features to search ranking models and populate business performance dashboards.",
                "responsibilities": "Construct daily Spark aggregation pipelines, manage schema evolution in Iceberg tables, and optimize Airflow DAG task schedules.",
                "salary_range": "$145,000 - $195,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Backend Developer",
                "department": "Reservations & Messaging Infrastructure",
                "employment_type": "Full-time",
                "location": "Austin, TX (Remote)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Node.js", "Python", "REST APIs", "PostgreSQL", "Redis", "Docker"],
                "preferred_skills": ["Java", "Distributed Locking", "Kafka Event Streams", "gRPC"],
                "description": "Develop low-latency messaging backends and atomic booking state machines processing millions of guest-host interactions per day.",
                "responsibilities": "Write distributed transactional APIs, maintain WebSocket connection fleets for real-time chat, and implement idempotent booking state engines.",
                "salary_range": "$155,000 - $210,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Tesla",
        "email": "careers@tesla.com",
        "password": "Password123!",
        "industry": "Automotive, Clean Energy & Robotics",
        "website": "https://www.tesla.com/careers",
        "jobs": [
            {
                "title": "Embedded Systems Engineer",
                "department": "Autopilot & Vehicle Controller Firmware",
                "employment_type": "Full-time",
                "location": "Palo Alto, CA (On-site)",
                "experience_required": 4,
                "education_required": "Bachelor's or Master's in Electrical Engineering, Computer Engineering",
                "required_skills": ["C", "C++", "RTOS", "Microcontrollers", "Embedded Linux", "I2C/SPI"],
                "preferred_skills": ["CAN/LIN Bus", "Bootloaders", "FreeRTOS", "Safety Critical (ISO 26262)"],
                "description": "Write deterministic, ultra-low latency C/C++ firmware controlling motor inverters, battery management systems (BMS), and Autopilot compute boards.",
                "responsibilities": "Develop board support packages (BSP), implement CAN communication layers, and debug high-voltage sensor interfaces with hardware oscilloscopes.",
                "salary_range": "$160,000 - $225,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Machine Learning Engineer",
                "department": "Tesla Vision & Full Self-Driving (FSD)",
                "employment_type": "Full-time",
                "location": "Palo Alto, CA (On-site)",
                "experience_required": 4,
                "education_required": "Master's or Ph.D. in Computer Vision, Machine Learning, or Robotics",
                "required_skills": ["Python", "PyTorch", "TensorFlow", "MLOps", "Docker", "NLP"],
                "preferred_skills": ["Occupancy Networks", "C++ Model Quantization (TensorRT)", "Dojo Supercomputer"],
                "description": "Train end-to-end neural networks for Full Self-Driving vehicles, processing raw camera video streams into driving trajectory vectors in real time.",
                "responsibilities": "Train spatial-temporal vision foundation models, quantize models for vehicle FSD inference silicon, and build automated video labeling pipelines.",
                "salary_range": "$175,000 - $250,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "DevOps Engineer",
                "department": "Fleet Telemetry & Over-The-Air (OTA) Cloud",
                "employment_type": "Full-time",
                "location": "Austin, TX (On-site)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science, Systems Engineering, or equivalent",
                "required_skills": ["Docker", "Kubernetes", "CI/CD", "AWS", "Terraform", "Linux"],
                "preferred_skills": ["High-Bandwidth Ingestion", "Ansible", "Fleet Provisioning", "Prometheus"],
                "description": "Scale global telemetry ingestion clusters streaming gigabytes of real-time sensor metrics and crash video logs from millions of vehicles worldwide.",
                "responsibilities": "Manage Kubernetes clusters handling millions of MQTT connections, automate fleet firmware OTA rollouts, and ensure 24/7 cloud reliability.",
                "salary_range": "$150,000 - $205,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Software Engineer",
                "department": "Energy Storage & Megapack Control Software",
                "employment_type": "Full-time",
                "location": "Palo Alto, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Python", "Java", "Git", "REST APIs", "SQL", "Data Structures"],
                "preferred_skills": ["Go", "Distributed Energy Optimization", "Industrial SCADA Protocols"],
                "description": "Build cloud control software and market bidding algorithms for utility-scale Megapack battery storage systems stabilizing the electric grid.",
                "responsibilities": "Develop real-time bidding services for energy trading markets, design fault-tolerant grid sync microservices, and optimize storage dispatch.",
                "salary_range": "$150,000 - $210,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Network Engineer",
                "department": "Gigafactory Factory Automation & Industrial Mesh",
                "employment_type": "Full-time",
                "location": "Austin, TX (On-site)",
                "experience_required": 4,
                "education_required": "Bachelor's in Network Engineering, Electrical, or CS",
                "required_skills": ["Cisco", "Routing & Switching", "TCP/IP", "Firewalls", "VPN", "Wireshark"],
                "preferred_skills": ["Industrial Ethernet", "OT/IT Network Segmentation", "802.1X Authentication"],
                "description": "Design high-reliability industrial networking architectures connecting robotic assembly arms, AGVs, and testing stations across Gigafactory manufacturing plants.",
                "responsibilities": "Deploy low-latency industrial switches, configure robust firewall isolation between OT and corporate networks, and troubleshoot packet loss.",
                "salary_range": "$140,000 - $190,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "NVIDIA",
        "email": "careers@nvidia.com",
        "password": "Password123!",
        "industry": "GPU Computing, AI Hardware & Accelerated Software",
        "website": "https://www.nvidia.com/careers",
        "jobs": [
            {
                "title": "Machine Learning Engineer",
                "department": "TensorRT & Large Model Acceleration",
                "employment_type": "Full-time",
                "location": "Santa Clara, CA (Hybrid)",
                "experience_required": 4,
                "education_required": "Master's or Ph.D. in Computer Science, Computer Engineering, or AI",
                "required_skills": ["Python", "PyTorch", "TensorFlow", "MLOps", "Docker", "NLP"],
                "preferred_skills": ["CUDA", "TensorRT-LLM", "Kernel Optimization", "FP8 / INT4 Quantization"],
                "description": "Optimize leading frontier LLMs, diffusion models, and multi-modal transformers for maximum throughput on NVIDIA Hopper and Blackwell GPU clusters.",
                "responsibilities": "Profile transformer inference bottlenecks, develop custom CUDA kernels and TensorRT plugins, and publish deep learning acceleration recipes.",
                "salary_range": "$180,000 - $260,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Software Engineer",
                "department": "CUDA Platform & Deep Learning Frameworks",
                "employment_type": "Full-time",
                "location": "Santa Clara, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's or Master's in Computer Science or Computer Engineering",
                "required_skills": ["Python", "Java", "Git", "REST APIs", "SQL", "Data Structures", "C++"],
                "preferred_skills": ["CUDA Programming", "Parallel Computing", "Memory Hierarchy Tuning"],
                "description": "Build high-performance C++ and Python bindings for CUDA libraries (cuDNN, cuBLAS, NCCL) utilized by AI researchers and supercomputing centers.",
                "responsibilities": "Design scalable parallel algorithms, optimize memory copy throughput between host and GPU device, and maintain backward-compatible runtime APIs.",
                "salary_range": "$165,000 - $235,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Embedded Systems Engineer",
                "department": "NVIDIA DRIVE Automotive SoC Firmware",
                "employment_type": "Full-time",
                "location": "Santa Clara, CA (On-site)",
                "experience_required": 4,
                "education_required": "Bachelor's in Electrical/Computer Engineering",
                "required_skills": ["C", "C++", "RTOS", "Microcontrollers", "Embedded Linux", "I2C/SPI"],
                "preferred_skills": ["QNX / SafeRTOS", "ARM Cortex-R5", "PCIe Root Complex", "ASIL-D"],
                "description": "Develop functional safety-compliant firmware and real-time operating system drivers for NVIDIA Orin and Thor automotive supercomputers.",
                "responsibilities": "Write device drivers for PCIe interfaces and high-resolution camera serializers, implement watchdog heartbeat monitors, and enforce ISO 26262 compliance.",
                "salary_range": "$160,000 - $225,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Network Engineer",
                "department": "Mellanox Quantum InfiniBand & AI Superclusters",
                "employment_type": "Full-time",
                "location": "Santa Clara, CA (On-site)",
                "experience_required": 4,
                "education_required": "Bachelor's in Networking, Computer Engineering, or CS",
                "required_skills": ["Cisco", "Routing & Switching", "TCP/IP", "Firewalls", "VPN", "Wireshark"],
                "preferred_skills": ["InfiniBand Architecture", "RoCE v2", "Spectrum-X Ethernet", "Ultra-Low Latency Fabrics"],
                "description": "Design and troubleshoot multi-thousand node InfiniBand and high-speed RoCE Ethernet networks connecting flagship AI supercomputers.",
                "responsibilities": "Configure non-blocking fat-tree topologies, optimize RDMA packet delivery rates, and diagnose congestion drops during multi-GPU model training.",
                "salary_range": "$155,000 - $215,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Cloud Solutions Architect",
                "department": "NVIDIA DGX Cloud Enterprise Systems",
                "employment_type": "Full-time",
                "location": "Austin, TX (Remote)",
                "experience_required": 5,
                "education_required": "Bachelor's in Computer Science or Information Systems",
                "required_skills": ["AWS", "Azure", "Cloud Architecture", "Terraform", "Docker", "Microservices"],
                "preferred_skills": ["Kubernetes (K8s)", "Slurm Workload Manager", "GPU Operator", "Multi-Cloud DGX"],
                "description": "Architect end-to-end AI training and inference cloud infrastructure across AWS, Azure, and Oracle Cloud powered by NVIDIA DGX Cloud.",
                "responsibilities": "Guide enterprise customers on deploying Kubernetes GPU operators, designing high-throughput network storage, and scaling Slurm clusters.",
                "salary_range": "$170,000 - $240,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "OpenAI",
        "email": "careers@openai.com",
        "password": "Password123!",
        "industry": "Frontier Artificial Intelligence & Research",
        "website": "https://openai.com/careers",
        "jobs": [
            {
                "title": "AI/NLP Engineer",
                "department": "Post-Training & RLHF Alignment",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 4,
                "education_required": "Master's or Ph.D. in AI, Computational Linguistics, or CS",
                "required_skills": ["NLP", "Transformers", "HuggingFace", "PyTorch", "LLMs", "Python"],
                "preferred_skills": ["Reinforcement Learning from Human Feedback (RLHF)", "DPO", "Reasoning Models", "Safety Alignment"],
                "description": "Conduct alignment research and fine-tuning experiments on frontier language models (GPT-4o, o1) to enhance reasoning capability, truthfulness, and safety.",
                "responsibilities": "Design reward modeling pipelines, execute large-scale RL training runs, and evaluate reasoning benchmarks across coding, mathematics, and science.",
                "salary_range": "$200,000 - $310,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Software Engineer",
                "department": "ChatGPT & API Platform Infrastructure",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Python", "Java", "Git", "REST APIs", "SQL", "Data Structures"],
                "preferred_skills": ["Streaming SSE", "Rate Limiting at Scale", "Rust", "High-Throughput APIs"],
                "description": "Build high-reliability developer APIs and backend infrastructure powering ChatGPT for over 200 million weekly active users.",
                "responsibilities": "Implement low-latency server-sent event (SSE) token streaming endpoints, design multi-tier token bucket rate limiters, and ensure 99.99% API reliability.",
                "salary_range": "$180,000 - $265,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Site Reliability Engineer",
                "department": "Frontier Training Cluster Reliability",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (On-site)",
                "experience_required": 5,
                "education_required": "Bachelor's in Computer Science or Systems Engineering",
                "required_skills": ["Kubernetes", "Prometheus", "Linux", "Incident Management", "Python", "Go", "CI/CD"],
                "preferred_skills": ["GPU Health Telemetry", "Infiniband Diagnostics", "Automated Node Remediation"],
                "description": "Maintain uninterrupted operation of massive multi-thousand GPU clusters training state-of-the-art frontier models.",
                "responsibilities": "Automate instant detection and replacement of failing GPU nodes, optimize distributed checkpoint I/O, and build automated cluster health remediators.",
                "salary_range": "$190,000 - $280,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Frontend Developer",
                "department": "ChatGPT Web & Canvas Interactive UI",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Interaction Design",
                "required_skills": ["React", "JavaScript", "TypeScript", "HTML/CSS", "Redux", "Tailwind"],
                "preferred_skills": ["Next.js", "Prosemirror / Rich Text Editors", "Real-time Collaboration (CRDTs)"],
                "description": "Design and build cutting-edge web interfaces for human-AI interaction, including ChatGPT Canvas, code execution previews, and multi-modal voice interfaces.",
                "responsibilities": "Develop real-time collaborative rich-text canvas components, optimize stream rendering performance, and craft responsive interactive elements.",
                "salary_range": "$170,000 - $240,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Cybersecurity Analyst",
                "department": "AI Security & Red Teaming",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 4,
                "education_required": "Bachelor's in Cybersecurity, Computer Science, or equivalent",
                "required_skills": ["Network Security", "SIEM", "Firewalls", "Threat Analysis", "Linux", "Python"],
                "preferred_skills": ["Prompt Injection Defense", "Adversarial Robustness", "Model Weight Security"],
                "description": "Lead adversarial evaluations and red-teaming against frontier models to discover jailbreaks, prompt injection vulnerabilities, and system attack vectors.",
                "responsibilities": "Perform automated adversarial testing against model weights, build real-time input sanitization guardrails, and harden model hosting infrastructure.",
                "salary_range": "$180,000 - $260,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Salesforce",
        "email": "careers@salesforce.com",
        "password": "Password123!",
        "industry": "Enterprise Cloud & Customer Relationship Management",
        "website": "https://www.salesforce.com/company/careers",
        "jobs": [
            {
                "title": "Cloud Solutions Architect",
                "department": "Salesforce Data Cloud & Einstein 1 Platform",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 5,
                "education_required": "Bachelor's in Computer Science or Information Systems",
                "required_skills": ["AWS", "Azure", "Cloud Architecture", "Terraform", "Docker", "Microservices"],
                "preferred_skills": ["Multi-Tenant SaaS Architecture", "Zero Copy Federation", "Enterprise Security"],
                "description": "Architect enterprise cloud solutions unifying fragmented CRM data across multi-tenant enterprise landscapes using Salesforce Data Cloud.",
                "responsibilities": "Design multi-tenant data ingestion pipelines, architect real-time unified customer profiles, and advise Fortune 100 enterprise CTOs.",
                "salary_range": "$165,000 - $225,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Business/Systems Analyst",
                "department": "Global Sales & Service Cloud Operations",
                "employment_type": "Full-time",
                "location": "Chicago, IL (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Business Administration, Information Systems, or Engineering",
                "required_skills": ["Requirements Gathering", "SQL", "Agile", "UML", "JIRA", "Business Process"],
                "preferred_skills": ["Salesforce Administrator Certified", "Process Flow Diagramming", "Executive Reporting"],
                "description": "Bridge business executives and engineering squads to translate enterprise sales, support, and quote-to-cash workflows into technical platform specifications.",
                "responsibilities": "Document complex business requirements, author user stories and acceptance criteria, and lead user acceptance testing (UAT) releases.",
                "salary_range": "$125,000 - $170,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Backend Developer",
                "department": "MuleSoft Integration & API Gateway",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Node.js", "Python", "REST APIs", "PostgreSQL", "Redis", "Docker", "Java"],
                "preferred_skills": ["MuleSoft Anypoint Platform", "OAS 3.0", "OAuth2 Token Validation", "gRPC"],
                "description": "Develop high-throughput API gateway connectors and enterprise integration runtimes orchestrating secure data exchange between legacy systems and modern SaaS.",
                "responsibilities": "Build high-concurrency API proxy handlers in Java/Node, optimize connection pooling, and enforce strict token encryption standards.",
                "salary_range": "$145,000 - $200,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "QA/Test Automation Engineer",
                "department": "Einstein AI & Platform Regression Automation",
                "employment_type": "Full-time",
                "location": "Bellevue, WA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Selenium", "Cypress", "TestNG", "Python", "JIRA", "CI/CD"],
                "preferred_skills": ["Playwright", "Automated Accessibility Testing", "API Automation"],
                "description": "Build automated test suites validating lightning component rendering, enterprise data permissions, and AI agent recommendations across monthly releases.",
                "responsibilities": "Author automated regression test plans, run parallel test execution grids, and isolate regressions before major seasonal platform deployments.",
                "salary_range": "$125,000 - $170,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Adobe",
        "email": "careers@adobe.com",
        "password": "Password123!",
        "industry": "Creative Cloud, Digital Media & Document Technology",
        "website": "https://www.adobe.com/careers",
        "jobs": [
            {
                "title": "Frontend Developer",
                "department": "Photoshop on the Web & WebAssembly Engine",
                "employment_type": "Full-time",
                "location": "San Jose, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Web Engineering",
                "required_skills": ["React", "JavaScript", "TypeScript", "HTML/CSS", "Redux", "Tailwind"],
                "preferred_skills": ["WebAssembly (Wasm)", "WebGL / WebGPU", "Canvas 2D Rendering", "Performance Optimization"],
                "description": "Bring professional desktop-class creative tooling to browser environments by compiling core Photoshop C++ image algorithms into WebAssembly with React UI.",
                "responsibilities": "Develop modular canvas editing interfaces, implement WebAssembly glue code, and achieve 60fps rendering during multi-layer brush strokes.",
                "salary_range": "$145,000 - $200,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "AI/NLP Engineer",
                "department": "Adobe Firefly Generative AI",
                "employment_type": "Full-time",
                "location": "San Jose, CA (Hybrid)",
                "experience_required": 4,
                "education_required": "Master's or Ph.D. in Computer Vision, AI, or CS",
                "required_skills": ["NLP", "Transformers", "HuggingFace", "PyTorch", "LLMs", "Python"],
                "preferred_skills": ["Diffusion Models", "Text-to-Image / Video", "Prompt Understanding", "Commercial Safety Filter"],
                "description": "Train and optimize commercially safe generative AI models powering Adobe Firefly text-to-image, generative fill, and vector expansion features.",
                "responsibilities": "Fine-tune diffusion models on curated media datasets, design multilingual text prompt encoders, and minimize GPU inference latency.",
                "salary_range": "$170,000 - $245,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Full Stack Developer",
                "department": "Creative Cloud Collaboration & Version History",
                "employment_type": "Full-time",
                "location": "Seattle, WA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["React", "Node.js", "TypeScript", "PostgreSQL", "Docker", "Git"],
                "preferred_skills": ["Cloud Storage Sync", "Binary Asset Diffs", "GraphQL APIs"],
                "description": "Build real-time asset sharing and comment review workflows connecting desktop applications like Premiere Pro and Illustrator to Creative Cloud Web.",
                "responsibilities": "Develop React collaboration panels, author Node.js asset chunk upload servers, and manage high-speed asset metadata storage.",
                "salary_range": "$145,000 - $195,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "UI/UX Designer",
                "department": "Adobe Express & Mobile Creative Apps",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Interaction Design, Graphic Design, or HCI",
                "required_skills": ["Figma", "Adobe XD", "Wireframing", "User Research", "Prototyping"],
                "preferred_skills": ["Adobe Spectrum Design System", "Touch Interaction UX", "Motion Prototyping"],
                "description": "Design accessible, empowering creative editing workflows that allow anyone to create stunning social media graphics, flyers, and videos in seconds.",
                "responsibilities": "Prototype fast template browsing and AI-assisted layout manipulation, conduct usability testing sessions, and build component specs.",
                "salary_range": "$135,000 - $185,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Datadog",
        "email": "careers@datadog.com",
        "password": "Password123!",
        "industry": "Cloud Monitoring, APM & Observability",
        "website": "https://www.datadoghq.com/careers",
        "jobs": [
            {
                "title": "DevOps Engineer",
                "department": "Global Telemetry Ingestion & Cluster Infrastructure",
                "employment_type": "Full-time",
                "location": "New York, NY (Hybrid)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science, Systems Engineering, or equivalent",
                "required_skills": ["Docker", "Kubernetes", "CI/CD", "AWS", "Terraform", "Linux"],
                "preferred_skills": ["High-Volume Kafka", "eBPF", "Terraform Cloud", "Multi-Cloud Networking"],
                "description": "Operate hyper-scale Kubernetes and Kafka clusters streaming trillions of observability metrics, logs, and traces daily from global client infrastructures.",
                "responsibilities": "Automate multi-region AWS and Azure cloud provisioning, manage high-density Kubernetes worker pools, and tune Linux kernel networking parameters.",
                "salary_range": "$160,000 - $220,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Site Reliability Engineer",
                "department": "Real-Time Query Engine & Incident Operations",
                "employment_type": "Full-time",
                "location": "Boston, MA (Hybrid)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science or Systems Engineering",
                "required_skills": ["Kubernetes", "Prometheus", "Linux", "Incident Management", "Python", "Go", "CI/CD"],
                "preferred_skills": ["Grafana", "Distributed Tracing (OpenTelemetry)", "SLO Engineering"],
                "description": "Ensure zero-downtime availability for Datadog's live dashboard query engines and real-time anomaly alerting pipelines.",
                "responsibilities": "Conduct incident reviews, implement automated self-healing scripts in Go and Python, and monitor planetary-scale metric aggregators.",
                "salary_range": "$155,000 - $215,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Cybersecurity Analyst",
                "department": "Cloud SIEM & Threat Hunting Engine",
                "employment_type": "Full-time",
                "location": "New York, NY (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Information Security, Computer Science, or related",
                "required_skills": ["Network Security", "SIEM", "Firewalls", "Threat Analysis", "Linux", "Python"],
                "preferred_skills": ["Cloud Security Posture Management (CSPM)", "MITRE ATT&CK", "YARA Rules"],
                "description": "Develop automated cloud security detection rules and investigate emerging attacker techniques across AWS, GCP, and Kubernetes ecosystems.",
                "responsibilities": "Author detection logic for Cloud SIEM, analyze cloud audit trails for suspicious privilege escalation, and support customer threat responses.",
                "salary_range": "$145,000 - $195,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Software Engineer",
                "department": "OpenTelemetry & Agent Runtime",
                "employment_type": "Full-time",
                "location": "New York, NY (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Python", "Java", "Git", "REST APIs", "SQL", "Data Structures", "Go"],
                "preferred_skills": ["eBPF Tracing", "C / Go System Internals", "Low Overhead Profiling"],
                "description": "Develop low-overhead telemetry collection agents deployed across millions of customer hosts, containers, and serverless environments.",
                "responsibilities": "Write high-performance Go/C code, capture kernel-level system metrics with eBPF, and optimize memory footprint on customer hosts.",
                "salary_range": "$155,000 - $210,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Snowflake",
        "email": "careers@snowflake.com",
        "password": "Password123!",
        "industry": "Data Cloud, Data Warehousing & Analytics",
        "website": "https://careers.snowflake.com",
        "jobs": [
            {
                "title": "Database Administrator",
                "department": "Virtual Warehouse & Query Engine Optimization",
                "employment_type": "Full-time",
                "location": "San Mateo, CA (Hybrid)",
                "experience_required": 5,
                "education_required": "Bachelor's in Computer Science, Database Systems, or equivalent",
                "required_skills": ["PostgreSQL", "MySQL", "Database Tuning", "SQL", "Backup & Recovery"],
                "preferred_skills": ["Columnar Storage Formats", "Query Compilation", "Micro-Partitioning"],
                "description": "Optimize multi-tenant database internals, query execution planners, and automated micro-partition metadata pruning for Snowflake Data Cloud.",
                "responsibilities": "Benchmark query plans, tune transactional consistency managers, and optimize distributed storage compaction routines.",
                "salary_range": "$165,000 - $235,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Data Engineer",
                "department": "Snowpipe & Streaming Data Ingestion",
                "employment_type": "Full-time",
                "location": "Bellevue, WA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Data Science, Computer Science, or Math",
                "required_skills": ["SQL", "Apache Spark", "Python", "ETL Pipelines", "Kafka", "BigQuery"],
                "preferred_skills": ["Snowpipe Streaming", "Dynamic Tables", "Change Data Capture (CDC)"],
                "description": "Build high-throughput streaming ingestion microservices that load millions of incoming files and Kafka messages into Snowflake with sub-second latency.",
                "responsibilities": "Design real-time ingestion pipelines, manage CDC replication streams, and optimize columnar parquet write performance.",
                "salary_range": "$150,000 - $205,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Software Engineer",
                "department": "Cortex AI & LLM Query Functions",
                "employment_type": "Full-time",
                "location": "San Mateo, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Python", "Java", "Git", "REST APIs", "SQL", "Data Structures", "C++"],
                "preferred_skills": ["LLM Serverless Inference", "Vector Search Integration", "vLLM"],
                "description": "Integrate cutting-edge LLMs and vector search functions directly into SQL query compilation engines for enterprise data analysis.",
                "responsibilities": "Develop scalable inference runtime plugins, enable native vector distance computations in SQL, and maintain enterprise data governance boundaries.",
                "salary_range": "$165,000 - $230,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Backend Developer",
                "department": "Cloud Infrastructure & Security Identity",
                "employment_type": "Full-time",
                "location": "San Mateo, CA (Remote)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Node.js", "Python", "REST APIs", "PostgreSQL", "Redis", "Docker", "Java"],
                "preferred_skills": ["SAML / SCIM Provisioning", "Role-Based Access Control (RBAC)", "Distributed Keys"],
                "description": "Build identity federation and enterprise access control services protecting petabytes of confidential enterprise data.",
                "responsibilities": "Design secure authentication microservices, implement row-level security policy evaluators, and author audit logging pipelines.",
                "salary_range": "$155,000 - $215,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Coinbase",
        "email": "careers@coinbase.com",
        "password": "Password123!",
        "industry": "Cryptocurrency & Web3 Financial Infrastructure",
        "website": "https://www.coinbase.com/careers",
        "jobs": [
            {
                "title": "Blockchain Developer",
                "department": "Base Layer 2 & Smart Contracts",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Cryptography",
                "required_skills": ["Solidity", "Ethereum", "Smart Contracts", "Web3.js", "Rust", "Python"],
                "preferred_skills": ["Optimistic Rollups / OP Stack", "EVM Internals", "Foundry / Hardhat", "Security Auditing"],
                "description": "Engineer core protocols and smart contracts on Base (Ethereum Layer 2) and build scalable bridging infrastructure connecting multi-chain ecosystems.",
                "responsibilities": "Write and audit gas-optimized Solidity smart contracts, maintain L1/L2 rollup sequencers, and build secure cross-chain messaging relays.",
                "salary_range": "$165,000 - $240,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Software Engineer",
                "department": "Crypto Trading Exchange & Matching Engine",
                "employment_type": "Full-time",
                "location": "New York, NY (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Python", "Java", "Git", "REST APIs", "SQL", "Data Structures", "Go"],
                "preferred_skills": ["Ultra-Low Latency Order Books", "Lock-Free Ring Buffers", "FIX Protocol"],
                "description": "Build high-speed, deterministic order matching engines processing millions of bids, asks, and crypto trades per second with zero drift.",
                "responsibilities": "Develop ultra-fast Go/Java matching microservices, implement distributed lock-free ring buffers, and ensure sub-millisecond trade execution.",
                "salary_range": "$160,000 - $225,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Cybersecurity Analyst",
                "department": "Cold Storage & Key Management Security",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 4,
                "education_required": "Bachelor's in Cybersecurity, Computer Science, or Cryptography",
                "required_skills": ["Network Security", "SIEM", "Firewalls", "Threat Analysis", "Linux", "Python"],
                "preferred_skills": ["Hardware Security Modules (HSM)", "Multi-Party Computation (MPC)", "Crypto Asset Custody"],
                "description": "Protect billions of dollars in digital asset reserves by defending cryptographic key management systems and automated transaction signing policies.",
                "responsibilities": "Audit MPC cryptographic signing ceremony protocols, monitor on-chain transaction anomaly detectors, and conduct security reviews of custodial systems.",
                "salary_range": "$160,000 - $220,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Mobile App Developer",
                "department": "Coinbase Wallet & Web3 dApp Browser",
                "employment_type": "Full-time",
                "location": "Austin, TX (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Mobile Engineering",
                "required_skills": ["Flutter", "React Native", "iOS", "Android", "Swift", "Kotlin"],
                "preferred_skills": ["Secure Enclave Key Storage", "EIP-1193 Provider", "Passkey / Smart Wallet"],
                "description": "Develop self-custody mobile crypto wallet features allowing users worldwide to trade tokens, collect NFTs, and interact with decentralized apps safely.",
                "responsibilities": "Engineer biometric key generation in Secure Enclave, develop smart wallet passkey account abstraction, and ensure flawless UI responsiveness.",
                "salary_range": "$150,000 - $205,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "GitHub",
        "email": "careers@github.com",
        "password": "Password123!",
        "industry": "Developer Tools, Open Source & Version Control",
        "website": "https://github.com/about/careers",
        "jobs": [
            {
                "title": "Full Stack Developer",
                "department": "GitHub Copilot Workspace & Pull Requests",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["React", "Node.js", "TypeScript", "PostgreSQL", "Docker", "Git"],
                "preferred_skills": ["Ruby on Rails", "Primer Design System", "WebSocket Realtime Diffs"],
                "description": "Design interactive AI coding experiences and rich pull request code review workflows used by over 100 million software developers.",
                "responsibilities": "Build real-time code split-diff views, develop Copilot AI suggestion integration panels, and optimize page load performance across large repositories.",
                "salary_range": "$150,000 - $210,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "DevOps Engineer",
                "department": "GitHub Actions & Hosted Runners Fleet",
                "employment_type": "Full-time",
                "location": "Seattle, WA (Remote)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science or Systems Engineering",
                "required_skills": ["Docker", "Kubernetes", "CI/CD", "AWS", "Terraform", "Linux", "Azure"],
                "preferred_skills": ["Ephemeral VM Orchestration", "Hyper-V / KVM", "Runner Image Automation"],
                "description": "Scale and secure the planetary computing fleet behind GitHub Actions, executing hundreds of millions of CI/CD build minutes every month.",
                "responsibilities": "Automate rapid provisioning of isolated ephemeral virtual machines, harden container isolation boundaries, and monitor global build queue latency.",
                "salary_range": "$155,000 - $215,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Backend Developer",
                "department": "Git Storage Engine & Spoke Cluster",
                "employment_type": "Full-time",
                "location": "New York, NY (Remote)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Node.js", "Python", "REST APIs", "PostgreSQL", "Redis", "Docker", "Go"],
                "preferred_skills": ["C / Git Internals", "Custom RPC Protocols", "Replication Mesh"],
                "description": "Build high-availability distributed storage clusters storing and replicating billions of Git repositories and commit trees with instant sync.",
                "responsibilities": "Develop high-throughput Git RPC daemons in Go/C, optimize delta-compression routines, and prevent split-brain partition anomalies.",
                "salary_range": "$160,000 - $225,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Site Reliability Engineer",
                "department": "Core Availability & DNS Edge Routing",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 4,
                "education_required": "Bachelor's in Computer Science or Systems Engineering",
                "required_skills": ["Kubernetes", "Prometheus", "Linux", "Incident Management", "Python", "Go", "CI/CD"],
                "preferred_skills": ["BGP Anycast", "Fastly / Cloudflare Edge", "Failover Drills"],
                "description": "Ensure five-nines uptime for github.com and global Git SSH/HTTPS clone endpoints across high-profile international traffic surges.",
                "responsibilities": "Mitigate multi-terabit DDoS attacks, maintain edge BGP Anycast routing configs, and lead root-cause post-mortem analyses.",
                "salary_range": "$155,000 - $215,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Shopify",
        "email": "careers@shopify.com",
        "password": "Password123!",
        "industry": "Global E-Commerce Platforms & Merchant Solutions",
        "website": "https://www.shopify.com/careers",
        "jobs": [
            {
                "title": "Backend Developer",
                "department": "High-Volume Flash Sale Checkout",
                "employment_type": "Full-time",
                "location": "Toronto, Canada (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Node.js", "Python", "REST APIs", "PostgreSQL", "Redis", "Docker"],
                "preferred_skills": ["Ruby on Rails", "Trident Inventory Engine", "High Concurrency DB Sharding"],
                "description": "Architect checkout backends designed to sustain extreme Black Friday flash sales processing over $40,000 in orders per second with zero inventory overselling.",
                "responsibilities": "Write lock-free inventory decrementing algorithms in Redis/MySQL, develop distributed order ingestion queues, and load test extreme traffic spikes.",
                "salary_range": "$140,000 - $190,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Frontend Developer",
                "department": "Online Store Customizer & Polaris Components",
                "employment_type": "Full-time",
                "location": "Ottawa, Canada (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Web Engineering",
                "required_skills": ["React", "JavaScript", "TypeScript", "HTML/CSS", "Redux", "Tailwind"],
                "preferred_skills": ["Shopify Polaris", "Liquid Template Engine", "Web Performance Optimization"],
                "description": "Build interactive merchant store builders and reusable Polaris UI components powering millions of independent storefronts worldwide.",
                "responsibilities": "Develop drag-and-drop live preview customizers in React, maintain high accessibility compliance, and profile DOM rendering bottlenecks.",
                "salary_range": "$135,000 - $185,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Data Scientist",
                "department": "Merchant Growth & Fraud Detection",
                "employment_type": "Full-time",
                "location": "Toronto, Canada (Remote)",
                "experience_required": 3,
                "education_required": "Master's or Bachelor's in Statistics, Data Science, or CS",
                "required_skills": ["Python", "R", "Machine Learning", "SQL", "Statistics", "Pandas"],
                "preferred_skills": ["Fraud Scoring Models", "Customer Lifetime Value (LTV)", "Tree-based Models (XGBoost)"],
                "description": "Build statistical machine learning models that detect fraudulent orders, evaluate merchant creditworthiness for Shopify Capital, and predict merchant churn.",
                "responsibilities": "Train gradient-boosted decision trees for transaction risk scoring, analyze merchant revenue cohorts, and deploy models in production.",
                "salary_range": "$145,000 - $195,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Database Administrator",
                "department": "Merchant Pod Database Architecture",
                "employment_type": "Full-time",
                "location": "Vancouver, Canada (Remote)",
                "experience_required": 5,
                "education_required": "Bachelor's in Computer Science or Information Technology",
                "required_skills": ["PostgreSQL", "MySQL", "Database Tuning", "SQL", "Backup & Recovery"],
                "preferred_skills": ["MySQL Pod Architecture", "Vitess / ProxySQL", "Automated Failover Orchestration"],
                "description": "Manage thousands of MySQL database pods that isolate merchant data and guarantee instant horizontal scaling across global data regions.",
                "responsibilities": "Optimize query execution performance, manage zero-downtime MySQL major version upgrades, and test automated disaster failover topologies.",
                "salary_range": "$145,000 - $200,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Atlassian",
        "email": "careers@atlassian.com",
        "password": "Password123!",
        "industry": "Team Collaboration, Agile Tools & Enterprise Software",
        "website": "https://www.atlassian.com/company/careers",
        "jobs": [
            {
                "title": "Business/Systems Analyst",
                "department": "Jira Product Discovery & Enterprise Agile Workflows",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Business Information Systems or Software Engineering",
                "required_skills": ["Requirements Gathering", "SQL", "Agile", "UML", "JIRA", "Business Process"],
                "preferred_skills": ["Scaled Agile Framework (SAFe)", "Workflow Automation", "Confluence Documentation"],
                "description": "Analyze team collaboration bottlenecks and translate modern Agile project management methodologies into feature requirements for Jira.",
                "responsibilities": "Author user story roadmaps, model cross-functional team dependency matrices, and run structured stakeholder requirement workshops.",
                "salary_range": "$130,000 - $175,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Full Stack Developer",
                "department": "Confluence Real-Time Collaborative Editor",
                "employment_type": "Full-time",
                "location": "Austin, TX (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["React", "Node.js", "TypeScript", "PostgreSQL", "Docker", "Git"],
                "preferred_skills": ["Operational Transformation / CRDT", "ProseMirror", "Atlassian Design System"],
                "description": "Build high-performance real-time collaborative document editing features enabling thousands of concurrent team members to co-author pages smoothly.",
                "responsibilities": "Develop ProseMirror editor plugins in TypeScript/React, manage WebSocket co-authoring synchronization servers, and optimize document load latency.",
                "salary_range": "$145,000 - $195,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "QA/Test Automation Engineer",
                "department": "Jira Service Management Platform Quality",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Remote)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Information Technology",
                "required_skills": ["Selenium", "Cypress", "TestNG", "Python", "JIRA", "CI/CD"],
                "preferred_skills": ["Playwright", "Contract Testing (Pact)", "Automated Load Testing (k6)"],
                "description": "Architect automated testing harnesses ensuring high availability and zero regressions across enterprise IT service desk workflows.",
                "responsibilities": "Write comprehensive automated end-to-end Cypress/Playwright suites, integrate test stages into CI/CD pipelines, and conduct SLA load benchmarking.",
                "salary_range": "$125,000 - $170,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
    {
        "company_name": "Figma",
        "email": "careers@figma.com",
        "password": "Password123!",
        "industry": "Collaborative Design, Vector Graphics & Web Platforms",
        "website": "https://www.figma.com/careers",
        "jobs": [
            {
                "title": "Frontend Developer",
                "department": "WebAssembly Vector Rendering Engine",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Computer Graphics",
                "required_skills": ["React", "JavaScript", "TypeScript", "HTML/CSS", "Redux", "Tailwind"],
                "preferred_skills": ["C++ to WebAssembly (Wasm)", "WebGL 2.0 / WebGPU", "Vector Math & Computational Geometry"],
                "description": "Push the boundaries of browser performance by building the core collaborative vector rendering engine and interactive design canvas in Figma.",
                "responsibilities": "Write high-performance TypeScript and C++ WebAssembly rendering code, optimize 120fps canvas rendering, and maintain collaborative multiplayer states.",
                "salary_range": "$165,000 - $235,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "UI/UX Designer",
                "department": "Figma Dev Mode & Design Systems",
                "employment_type": "Full-time",
                "location": "San Francisco, CA (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Interaction Design, HCI, or Design",
                "required_skills": ["Figma", "Adobe XD", "Wireframing", "User Research", "Prototyping"],
                "preferred_skills": ["Developer Tooling UX", "Figma Variables & Auto Layout", "Code Generation Inspection"],
                "description": "Design revolutionary developer handoff interfaces in Figma Dev Mode that translate design tokens, components, and layouts directly into code.",
                "responsibilities": "Conduct qualitative interviews with frontend engineers, design intuitive property inspectors, and advance Figma's internal design system.",
                "salary_range": "$150,000 - $210,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
            {
                "title": "Software Engineer",
                "department": "Multiplayer Synchronization & CRDT Backend",
                "employment_type": "Full-time",
                "location": "New York, NY (Hybrid)",
                "experience_required": 3,
                "education_required": "Bachelor's in Computer Science or Software Engineering",
                "required_skills": ["Python", "Java", "Git", "REST APIs", "SQL", "Data Structures", "Go"],
                "preferred_skills": ["Conflict-Free Replicated Data Types (CRDT)", "Rust", "WebSocket Realtime Servers"],
                "description": "Build high-throughput backend infrastructure that synchronizes design changes across millions of concurrent multiplayer users with zero merge conflicts.",
                "responsibilities": "Develop distributed real-time sync servers in Rust/Go, design spatial tree indexing structures, and maintain microsecond message delivery.",
                "salary_range": "$165,000 - $230,000 / year",
                "status": "open",
                "interview_required": True,
                "interview_question_count": 10,
            },
        ],
    },
]

def seed_70():
    print(f"Connecting to MongoDB: {DB_NAME}")
    now = datetime.now(timezone.utc)
    new_companies_count = 0
    new_jobs_count = 0

    for comp in COMPANIES_70:
        email = comp["email"].lower().strip()
        existing = db.users.find_one({"email": email})
        if existing:
            company_id = existing["_id"]
            db.users.update_one(
                {"_id": company_id},
                {"$set": {
                    "role": "company",
                    "company_name": comp["company_name"],
                    "full_name": comp["company_name"],
                    "industry": comp["industry"],
                    "website": comp["website"],
                    "password": hash_pw(comp["password"]),
                    "updated_at": now,
                }}
            )
            print(f"Updated company: {comp['company_name']} ({email})")
        else:
            doc = {
                "role": "company",
                "company_name": comp["company_name"],
                "full_name": comp["company_name"],
                "email": email,
                "password": hash_pw(comp["password"]),
                "industry": comp["industry"],
                "website": comp["website"],
                "created_at": now,
            }
            res = db.users.insert_one(doc)
            company_id = res.inserted_id
            print(f"Created company: {comp['company_name']} ({email}) -> ID: {company_id}")
            new_companies_count += 1

        for job_data in comp["jobs"]:
            job_title = job_data["title"]
            job_dept = job_data.get("department", "")
            # Match by company_id and department/title to allow multiple specialized roles per company
            existing_job = db.jobs.find_one({"company_id": company_id, "title": job_title, "department": job_dept})
            job_doc = {
                "company_id": company_id,
                "title": job_title,
                "department": job_dept,
                "employment_type": job_data.get("employment_type", "Full-time"),
                "location": job_data.get("location", ""),
                "experience_required": job_data.get("experience_required", 0),
                "education_required": job_data.get("education_required", ""),
                "required_skills": job_data.get("required_skills", []),
                "preferred_skills": job_data.get("preferred_skills", []),
                "description": job_data.get("description", ""),
                "responsibilities": job_data.get("responsibilities", ""),
                "salary_range": job_data.get("salary_range", ""),
                "status": job_data.get("status", "open"),
                "interview_required": job_data.get("interview_required", True),
                "interview_question_count": job_data.get("interview_question_count", 10),
                "updated_at": now,
            }
            if existing_job:
                db.jobs.update_one({"_id": existing_job["_id"]}, {"$set": job_doc})
                print(f"  Updated job: {comp['company_name']} - {job_title} ({job_dept})")
            else:
                job_doc["created_at"] = now
                res_job = db.jobs.insert_one(job_doc)
                print(f"  Inserted job: {comp['company_name']} - {job_title} ({job_dept}) -> ID: {res_job.inserted_id}")
                new_jobs_count += 1

    total_companies = db.users.count_documents({"role": "company"})
    total_jobs = db.jobs.count_documents({})
    print("\n==========================================")
    print(f"Added {new_jobs_count} new job postings across {len(COMPANIES_70)} companies!")
    print(f"Total Companies now in Database: {total_companies}")
    print(f"Total Jobs now in Database: {total_jobs}")
    print("==========================================\n")

if __name__ == "__main__":
    seed_70()
